# Generated by Django 5.2.4 on 2025-07-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_active',
            new_name='is_activate',
        ),
    ]
