# Generated by Django 5.2.4 on 2025-08-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_rename_is_active_category_is_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
