# Generated by Django 5.2.4 on 2025-08-25 18:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0003_rename_is_activate_category_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='genres', to='category_app.category')),
            ],
            options={
                'db_table': 'genre',
            },
        ),
    ]
